# Generated by Django 3.1.7 on 2021-03-08 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 19, 14, 31, 408956)),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='event_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
